# Generated by Django 4.1 on 2022-09-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_remove_movie_reviews_moviereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='review',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review',
            field=models.ManyToManyField(to='movie_app.review'),
        ),
    ]
