# Generated by Django 4.1 on 2022-10-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_alter_moviereview_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='m_c',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='movie_count', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='review',
            field=models.ManyToManyField(related_name='review', to='movie_app.review'),
        ),
    ]
